### ISSUE TITLE
Division by zero error for scalar variables

### ISSUE THREAD

**Issue by aidanheerdegen** [aidanheerdegen/nccompress#1]
Got this error:
```python
Traceback (most recent call last):
  File "/projects/access/apps/nccompress/0.1/bin/nc2nc", line 363, in <module>
    verbose=verbose, vars=args.vars, classic=args.classic, buffersize=args.buffersize, ignoreformat=args.ignoreformat)
  File "/projects/access/apps/nccompress/0.1/bin/nc2nc", line 258, in nc2nc
    chunksizes=chunk_shape_nD(ncvar.shape,valSize=dtypes[ncvar.dtype.char],minDim=mindim)
  File "/projects/access/apps/nccompress/0.1/bin/nc2nc", line 110, in chunk_shape_nD
    chunkShape = ma.array(calcChunkShape(chunkVals,varShapema),dtype=int)
  File "/projects/access/apps/nccompress/0.1/bin/nc2nc", line 85, in calcChunkShape
    return np.array(cascadeRounding(np.asarray(varShape) * (chunkVol / float(numVals(varShape))) ** (1./len(varShape))),dtype="int")
ZeroDivisionError: float division by zero
```
When processing a netcdf file with variables like this:
```netcdf
        double P0 ;
                P0:long_name = "reference pressure" ;
                P0:units = "Pa" ;
```

**Comment by aidanheerdegen** [comment]
Fixed.

https://github.com/aidanheerdegen/nccompress/commit/aa91b32bcd4fe016008e7fd13821656c66cd1f49
